[package]
name = "NFTMarketplace"
version = "0.1.0"

[addresses]
NFTMarketplace = "0xe0c2e76c204c24aecc40430e9ece251d8fcb0b5a55aa62fab0aa9ec5441a27b4"
aptos_framework = "0x1"
primitives = "0xCAFE"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "main" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib", rev = "main" }